# Generated by Django 2.0.4 on 2018-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
