# Generated by Django 2.1.2 on 2018-10-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.IntegerField(choices=[(1, 'Chinese'), (2, 'North Indian'), (3, 'South Indian'), (4, 'Italian')], max_length=50),
        ),
    ]
