# Generated by Django 2.0.4 on 2018-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('N', 'Not Specified'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
    ]
