# Generated by Django 2.0.4 on 2018-09-29 06:31

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180929_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'English'), (2, 'Maths'), (3, 'C++'), (4, 'Physics')])),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='student',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Student.upload_to),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
